# NAME: Khoa Quach, Joshua Futterman
# EMAIL: khoaquachschool@gmail.com, joshafuttcomp23@ucla.edu
# ID: 105123806,505347668
.SILENT:
build:
	rm -f lab3b
	chmod +x lab3b.py
	-ln lab3b.py lab3b

clean:
	rm -f lab3b *.tar.gz

dist:
	tar -czvf lab3b-105123806.tar.gz lab3b.py Makefile README
